
import { Injectable, InternalServerErrorException, BadRequestException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { GoogleGenerativeAI } from '@google/generative-ai';

@Injectable()
export class AiImageService {
  private genAI: GoogleGenerativeAI;

  constructor(private configService: ConfigService) {
    const geminiKey = this.configService.get<string>('GEMINI_API_KEY');
    if (!geminiKey) {
      throw new Error('GEMINI_API_KEY is not configured');
    }
    this.genAI = new GoogleGenerativeAI(geminiKey);
  }

  async generateImage(prompt: string): Promise<{ imageUrl: string }> {
    try {
      if (!prompt.trim()) {
        throw new BadRequestException('Prompt cannot be empty');
      }

      const model = this.genAI.getGenerativeModel({
        model: 'gemini-2.0-flash-exp',
      });

      const result = await model.generateContent([
        `Generate a clear, educational diagram or illustration suitable for an online quiz question based on this prompt: "${prompt}". Use simple, professional style.`,
      ]);

      const response = await result.response;
      const parts = response.candidates?.[0]?.content?.parts || [];
      
      for (const part of parts) {
        if (part.inlineData) {
          const base64Data = part.inlineData.data;
          const mimeType = part.inlineData.mimeType || 'image/png';
          return { imageUrl: `data:${mimeType};base64,${base64Data}` };
        }
      }

      throw new InternalServerErrorException('No image was generated by Gemini AI');
    } catch (error) {
      console.error('Gemini image generation error:', error);
      throw new InternalServerErrorException('Failed to generate image using Gemini AI. Please try again.');
    }
  }
}
