
import { Injectable, InternalServerErrorException, BadRequestException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { GoogleGenerativeAI } from '@google/generative-ai';

@Injectable()
export class AiImageService {
  private genAI: GoogleGenerativeAI;

  constructor(private configService: ConfigService) {
    const geminiKey = this.configService.get<string>('GEMINI_API_KEY');
    if (!geminiKey) {
      throw new Error('GEMINI_API_KEY is required for image generation');
    }
    this.genAI = new GoogleGenerativeAI(geminiKey);
  }

  async generateImage(prompt: string): Promise<{ imageUrl: string }> {
    try {
      if (!prompt.trim()) {
        throw new BadRequestException('Prompt cannot be empty');
      }

      console.log('Starting image generation with prompt:', prompt);

      const model = this.genAI.getGenerativeModel({
        model: 'gemini-1.5-flash',
      });

      const result = await model.generateContent({
        contents: [
          {
            role: 'user',
            parts: [
              {
                text: `Generate a clear, educational diagram or illustration suitable for an online quiz question based on this prompt: "${prompt}". Use simple, professional style. Respond with ONLY the image, no extra text.`,
              },
            ],
          },
        ],
      });

      const response = await result.response;
      console.log('Gemini response received');

      const parts = response.candidates?.[0]?.content?.parts || [];
      console.log('Response parts:', parts.length, 'parts found');
      
      for (const part of parts) {
        if (part.inlineData) {
          const base64Data = part.inlineData.data;
          const mimeType = part.inlineData.mimeType || 'image/png';
          console.log('Generated image with mimeType:', mimeType);
          return { imageUrl: `data:${mimeType};base64,${base64Data}` };
        }
      }

      console.error('No inlineData in response');
      throw new InternalServerErrorException('No image was generated by Gemini AI');
    } catch (error) {
      console.error('Gemini image generation error:', error);
      if (error instanceof Error) {
        console.error('Error stack:', error.stack);
      }
      throw new InternalServerErrorException('Failed to generate image using Gemini AI. Please try again.');
    }
  }
}
