
import { Injectable, InternalServerErrorException, BadRequestException, OnModuleInit, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { GoogleGenerativeAI } from '@google/generative-ai';

@Injectable()
export class AiImageService implements OnModuleInit {
  private readonly logger = new Logger(AiImageService.name);
  private genAI: GoogleGenerativeAI;
  private readonly modelName = 'gemini-2.0-flash-exp';

  constructor(private configService: ConfigService) {}

  async onModuleInit() {
    const geminiKey = this.configService.get<string>('GEMINI_API_KEY');
    if (!geminiKey) {
      this.logger.error('Gemini initialization failed: GEMINI_API_KEY is not set');
      return;
    }

    try {
      this.genAI = new GoogleGenerativeAI(geminiKey);
      this.logger.log(`Gemini initialized successfully. Using model: ${this.modelName}`);
    } catch (error) {
      this.logger.error('Gemini initialization failed', error);
    }
  }

  async generateImage(prompt: string): Promise<{ imageUrl: string }> {
    try {
      if (!this.genAI) {
        throw new InternalServerErrorException('Gemini AI is not initialized. Please check your environment variables.');
      }

      if (!prompt.trim()) {
        throw new BadRequestException('Prompt cannot be empty');
      }

      this.logger.log('Starting image generation with prompt:', prompt);

      const model = this.genAI.getGenerativeModel({
        model: this.modelName,
      });

      const result = await model.generateContent({
        contents: [
          {
            role: 'user',
            parts: [
              {
                text: `Generate a clear, educational diagram or illustration suitable for an online quiz question based on this prompt: "${prompt}". Use simple, professional style. Respond with ONLY the image, no extra text.`,
              },
            ],
          },
        ],
      });

      const response = await result.response;
      this.logger.log('Gemini response received');

      const parts = response.candidates?.[0]?.content?.parts || [];
      this.logger.log(`Response parts: ${parts.length} parts found`);

      for (const part of parts) {
        if (part.inlineData) {
          const base64Data = part.inlineData.data;
          const mimeType = part.inlineData.mimeType || 'image/png';
          this.logger.log('Generated image with mimeType:', mimeType);
          return { imageUrl: `data:${mimeType};base64,${base64Data}` };
        }
      }

      this.logger.error('No inlineData in response');
      throw new InternalServerErrorException('No image was generated by Gemini AI');
    } catch (error) {
      this.logger.error('Gemini image generation error:', error);
      
      if (error instanceof BadRequestException) {
        throw error;
      }

      if (error instanceof Error) {
        if (error.message.includes('404')) {
          throw new InternalServerErrorException('Gemini model is currently unavailable. Please try again later.');
        }
        if (error.message.includes('401') || error.message.includes('403')) {
          throw new InternalServerErrorException('Gemini API key is invalid. Please check your configuration.');
        }
        if (error.message.includes('429')) {
          throw new InternalServerErrorException('Gemini rate limit exceeded. Please try again later.');
        }
      }

      throw new InternalServerErrorException('Failed to generate AI image. Please try again later.');
    }
  }
}
